### ISSUE TITLE
ERROR! Download URL for PPA is empty. Skipping.

### ISSUE THREAD

**Issue by M4rQu1Nh0S** [wimpysworld/deb-get#377] opened 2022-07-22 00:52 UTC
### Expected behavior

Packages in the PPA repository should normally be installed with the command `deb-get install package`

### Actual behavior

Error in Terminal:
`
[!] ERROR! Download URL for quickgui is empty. Skipping.
`

### Steps to reproduce

1. Install the version 0.3.2 of deb-get
2. Enter the command `deb-get install firefox-esr` (example)

### System information

Ubuntu 22.04 virtual machine

#### deb-get version

```
version 0.3.2
```

### Possible solution

1. Edit the deb-get file, and search for this section:
```
OS_CODENAME=$(lsb_release --codename --short)
if [ -e /etc/os-release ]; then
#Debian VERSION_CODENAME=$(grep VERSION_CODENAME /etc/os-release | cut -d'=' -f2 | sed 's/"//g')
    UPSTREAM_ID="$(grep "^ID=" /etc/os-release | cut -d'=' -f2)"
    UPSTREAM_ID_LIKE="$(grep "^ID_LIKE=" /etc/os-release | cut -d'=' -f2 | sed s/\"//g | cut -d' ' -f1)"
    if [ ! -z "${UPSTREAM_ID_LIKE}" ]; then
        UPSTREAM_ID="${UPSTREAM_ID_LIKE}"
    fi
    case "${UPSTREAM_ID}" in
        debian) UPSTREAM_CODENAME=$(grep VERSION_CODENAME /etc/os-release | cut -d'=' -f2);;
        ubuntu) UPSTREAM_CODENAME=$(grep UBUNTU_CODENAME /etc/os-release | cut -d'=' -f2);;
        *) UPSTREAM_CODENAME="";;
    esac
else
    fancy_message fatal "/etc/os-release not found. Quitting"
fi
```
2. Remove the following lines:
```
    if [ ! -z "${UPSTREAM_ID_LIKE}" ]; then
        UPSTREAM_ID="${UPSTREAM_ID_LIKE}"
    fi
```
3. save the changes and try install any PPA package with deb-get

**Comment by natanjunges** [comment] 2022-07-22 01:39
Duplicate of #365. A solution is already being worked on in #366.

**Closed** 2022-07-22 05:28 UTC
