### ISSUE TITLE
Search and show without sudo like apt

### ISSUE THREAD

**Issue by Paddy-NI** [wimpysworld/deb-get#160] opened 2022-05-12 20:43 UTC
On a standard Ubuntu install, you can open a terminal and type "apt search foo" and it will query and return results.

It would be wonderful if deb-get did the same.

This is also true when using "apt show foo".

**Comment by flexiondotorg** [comment] 2022-05-15 11:34
Duplicate of #33

**Closed by flexiondotorg** 2022-05-15 11:34 UTC
Labels: duplicate
