### ISSUE TITLE
0.3.3 breaks Linux Mint compatibility again

### ISSUE THREAD

**Issue by arxo** [wimpysworld/deb-get#389] opened 2022-07-26 16:51 UTC
Just like 0.3.1 broke compatibility with Linux Mint (which was fixed in 0.3.2), it is once again broken in 0.3.3.

### Expected behavior

deb-get 0.3.3 works when run unter Linux Mint 20.3

### Actual behavior

deb-get shows this error message when run:
  [!] ERROR! Linux Mint Una is not supported because it is not derived from a supported Debian or Ubuntu release.

### Steps to reproduce

just run "deb-get" with none or any parameters

### System information

Run the following a paste the output below:

#### /etc/os-release

NAME="Linux Mint"
VERSION="20.3 (Una)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.3"
VERSION_ID="20.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=una
UBUNTU_CODENAME=focal

#### /etc/lsb-release

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.3
DISTRIB_CODENAME=una
DISTRIB_DESCRIPTION="Linux Mint 20.3 Una"

#### deb-get version

prints error message, as shown above (but it is 0.3.3)

### deb-get update

prints error message, as shown above

### Just an idea...

Would it be possible to add some kind of CI tests, which run deb-get under different distros? That way regressions like this could be prevented.

**Comment by Xmetalfanx** [comment] 2022-07-26 21:13
I was taking a look to add something extra for Mint (not sure if that have been a good idea, anyway) but this may have been addressed with the merged commit https://github.com/wimpysworld/deb-get/commit/f091a1334d34dbd8777fef24480523ba4c602e2e  .. the deb-get team just hasn't released a 0.3.4 version as of yet, but if that commit works then this issue may already be fixed

**Comment by natanjunges** [comment] 2022-07-26 21:55
Duplicate of #384. Fixed via https://github.com/wimpysworld/deb-get/commit/fe4cb91c60535c438af685894a4093e58eb241d4.

**Closed** 2022-07-29 09:31 UTC
