### ISSUE TITLE
Requesting a new app: Gimp

### ISSUE THREAD

**Issue by M-Rick** [wimpysworld/deb-get#1005] opened 2024-02-10 16:31 UTC
## Requesting a new app ✨

 - [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Gimp
 - Download URL: https://ppa.launchpadcontent.net/ubuntuhandbook1/gimp/ubuntu/pool/main/g/gimp/gimp_2.10.36-0build1~ubuntu2310_amd64.deb
https://ppa.launchpadcontent.net/ubuntuhandbook1/gimp/ubuntu/pool/main/g/gimp/gimp_2.10.36-0build1~ubuntu2310_arm64.deb
 - Website URL: https://www.gimp.org/
 - App Summary: GIMP is a cross-platform image editor available for GNU/Linux, macOS, Windows used for image manipulation (retouching) and image editing, free-form drawing, transcoding between different image file formats, and more specialized tasks. It is extensible by means of plugins, and scriptable. It is not designed to be used for drawing, though some artists and creators have used it in this way.

On this launchpad, it is up-to-date compared to the official Debian and Ubuntu depots. The latest version available is the 2.10.34, while the launchpad has the latest 2.10.36 with a lot of new features.

```
sudo add-apt-repository -y ppa:ubuntuhandbook1/gimp && sudo apt update
sudo apt install -y gimp gimp-help-fr
```

**Comment by philclifford** [comment] 2024-02-11 16:08
duplicate of #1001

**Closed by philclifford** 2024-02-11 16:08 UTC
Labels: duplicate
