### ISSUE TITLE
should we add wine?

### ISSUE THREAD

**Issue by Fuseteam** [wimpysworld/deb-get#468] opened 2022-08-26 12:36 UTC
# Add wine?

## Requesting a new app ✨

If you are requesting a new app to be added to `deb-get` please complete the
following section, only one app per issue please.

 - [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: wine
 - Download URL: https://wiki.winehq.org/Ubuntu, https://wiki.winehq.org/Debian
 - Website URL: winehq.org
 - App Summary: the windows compatibility layer

i was thinking I could add wine as well as usually users install the one from winehq rather than the one is in the repo, but i wasn't quite sure we want it as we already have crossover in here. the location of the sources file seems to have a nice pattern we could use i think but it does differ between debian and ubuntu. while the key has one location.

Key: https://dl.winehq.org/wine-builds/winehq.key

Ubuntu | Sources file
-- | --
jammy | https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
focal   | https://dl.winehq.org/wine-builds/ubuntu/dists/focal/winehq-focal.sources

Debian |  Sources file
-- | --
Buster | https://dl.winehq.org/wine-builds/debian/dists/buster/winehq-buster.sources
Bullseye | https://dl.winehq.org/wine-builds/debian/dists/bullseye/winehq-bullseye.sources
Bookworm | https://dl.winehq.org/wine-builds/debian/dists/bookworm/winehq-bookworm.sources

**Comment by flexiondotorg** [comment] 2022-09-23 12:58
Duplicate of #427

**Closed by flexiondotorg** 2022-09-23 12:58 UTC
Labels: duplicate
