### ISSUE TITLE
"deb-get search" requires sudo to root

### ISSUE THREAD

**Issue by zoomosis** [wimpysworld/deb-get#35] opened 2022-05-05 03:41 UTC
This is probably an oversight but I don't think there's any fundamental reason why "deb-get search" should require root.

**Comment by zoomosis** [comment] 2022-05-05 03:44
Also just running "deb-get" without args is unhelpful:
```
[!] ERROR! You must use sudo to run deb-get.
```

**Comment by flexiondotorg** [comment] 2022-05-05 09:09
Duplicate of #33

**Closed by flexiondotorg** 2022-05-05 09:09 UTC
