### ISSUE TITLE
Add Whatsdesk

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#54] opened 2022-05-05 10:23 UTC
Whatsdesk is open source unofficial Whatsapp client
They have a deb available from their website.
https://zerkc.gitlab.io/whatsdesk/whatsdesk_0.3.8_amd64.deb

**Comment by flexiondotorg** [comment] 2022-05-08 22:32
Duplicate of #55. Whatsapp-for-Linux is a better-maintained project.

**Closed by flexiondotorg** 2022-05-08 22:32 UTC
