### ISSUE TITLE
Add support for the Google Cloud SDK

### ISSUE THREAD

**Issue by OhMyMndy** [wimpysworld/deb-get#499] opened 2022-09-04 18:35 UTC

**Comment by sachinsejwal** [comment] 2022-09-10 08:46
Hi @OhMyMndy ,
This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?

**Comment by AditSaxena** [comment] 2022-09-10 14:45
@flexiondotorg 
If the issue is open, I would like to work on it.

**Comment by natanjunges** [comment] 2022-09-12 16:44
#500 already implements this.

**Closed** 2022-09-19 08:56 UTC
Labels: good first issue, new package
