### ISSUE TITLE
Add Google-Chat-Linux

### ISSUE THREAD

**Issue by dtantono** [wimpysworld/deb-get#115] opened 2022-05-06 13:01 UTC
an unofficial Google Chat Client
They have a deb available from their website.
https://github.com/squalou/google-chat-linux/releases/download/5.15.17-1/google-chat-linux_5.15.17-1_amd64.deb

**Comment by flexiondotorg** [comment] 2022-05-08 12:22
Duplicate of #114. Only one Google Chat client is required in `deb-get` and Google-Chat-Eletron appears to be better maintained.

**Closed by flexiondotorg** 2022-05-08 12:22 UTC
Labels: duplicate
