### ISSUE TITLE
Fix for derivatives broke ppas for Ubuntus

### ISSUE THREAD

**Issue by philclifford** [wimpysworld/deb-get#365] opened 2022-07-20 10:56 UTC
Need to add an `or` - PR ready to test on derivatives and Debians
-----------
This broke `deb-get` 0.3.2, at least on Ubuntu MATE 22.04. `/etc/os-release` has 
```
ID=ubuntu
ID_LIKE=debian
```

The code provided by this PR then replaces `UPSTREAM_ID` with `debian`, which breaks all packages that install from a PPA, given they all look like this : 
```shell
function deb_copyq() {
    if [ "${UPSTREAM_ID}" == "ubuntu" ]; then
        PPA="ppa:hluk/copyq"
        PRETTY_NAME="CopyQ"
        WEBSITE="https://hluk.github.io/CopyQ/"
        SUMMARY="An advanced clipboard manager with editing and scripting features."
    fi
}
```
making it impossible to update or install packages from PPAs : 
```shell
sudo deb-get install copyq
  [!] ERROR! Download URL for copyq is empty. Skipping.
```

_Originally posted by @ymauray in https://github.com/wimpysworld/deb-get/issues/343#issuecomment-1190048523_

**Comment by ymauray** [comment] 2022-07-20 11:07
Thanks Phil. I just saw the email coming and thought "shoot, I updated the closed PR instead of creating an issue" !

**Comment by natanjunges** [comment] 2022-07-20 14:23
I looks like even in vanilla Ubuntu it does not work as intended, since it will also replace `UPSTREAM_ID` with `debian`.

**Comment by ymauray** [comment] 2022-07-20 14:48
Do we have a notion of urgency on github ? It seems to me that this bug is pretty critical, as all Ubuntu derivatives (and Mint) are now unable to install or update things from PPAs.

**Comment by Xmetalfanx** [comment] 2022-07-21 02:44
I had submitted a PR to fix the Strawberry space issue and after update + upgrading I noticed it still didn't work  with    ` fancy_message error "Download URL for ${APP} is empty. Skipping."` getting triggered ... just tested two other PPA items at random including obs and i am now seeing the same thing with them too _(was testing to see if my PR that was merged actually fixed the issue)_

**Closed** 2022-07-23 08:30 UTC
