### ISSUE TITLE
Support for Debian Testing/Sid and/or Debien 13 (Trixie)

### ISSUE THREAD

**Issue by Xdavius** [wimpysworld/deb-get#848] opened 2023-06-29 12:12 UTC
### Expected behavior

Support For Debian Testing / Trixie / Sid

### Actual behavior

Testing is not supported

### Steps to reproduce

deb-get update
deb-get upgrade

#### /etc/os-release

davius@davius-gladius:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
davius@davius-gladius:~$ 

#### deb-get version

Latest one but can't execute deb-get version : error

### deb-get update

davius@davius-gladius:~$ deb-get update
  [!] ERROR! Debian Trixie is not supported because it is not derived from a supported Debian or Ubuntu release.
davius@davius-gladius:~$

**Comment by philclifford** [comment] 2023-06-29 19:20
Duplicate of #839

**Closed** 2023-06-29 19:20 UTC
