### ISSUE TITLE
Fastfetch install fails

### ISSUE THREAD

**Issue by bshor** [wimpysworld/deb-get#1009] opened 2024-02-11 22:31 UTC
# deb-get issue template

### Expected behavior

Fastfetch installs

### Actual behavior

deb-get install fastfetch fails with the following error:

ERROR! Missing required information of github package fastfetch:
URL=
VERSION_PUBLISHED=

![image](https://github.com/wimpysworld/deb-get/assets/468070/5d8fe772-a6cb-4677-9880-a3540203ffc1)

### Steps to reproduce

deb-get install fastfetch

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

#### /etc/lsb-release

```bash
cat /etc/lsb-release
```

#### deb-get version

```bash
deb-get version
0.4.0
```

**Comment by philclifford** [comment] 2024-02-12 18:16
duplicate of #1008

**Closed by philclifford** 2024-02-12 18:16 UTC
Labels: duplicate
