### ISSUE TITLE
Add Deadbeef 

### ISSUE THREAD

**Issue by Xmetalfanx** [wimpysworld/deb-get#156] opened 2022-05-11 18:47 UTC
Homepage: https://deadbeef.sourceforge.io/
Github page: https://github.com/DeaDBeeF-Player/deadbeef
Download Page: https://deadbeef.sourceforge.io/download.html
Latest Sourceforge DEB link: https://sourceforge.net/projects/deadbeef/files/travis/linux/1.8.8/deadbeef-static_1.8.8-1_amd64.deb/download  (I know this can't be accepted now this cant be accepted due to how this seems hard-coded )

There are sourceforge links to DEBs though even in some of my own scripts I have setup I have not found a "good way" to always get the latest DEB via Sourceforge, so that may be an issue @ why it cant be added, I am guessing.

I suppose since they have "tags" on github but not releases (direct github DEB downloads) I could open an issue there and since they already have the DEBs, ask them if they'd upload the DEBs they make for each version tag TO github too and not just Sourceforge

**Comment by flexiondotorg** [comment] 2022-05-12 10:00
Duplicate of #53

**Closed by flexiondotorg** 2022-05-12 10:00 UTC
Labels: duplicate
