### ISSUE TITLE
BUG: dpkg -l is not a good test to see if a package is installed

### ISSUE THREAD

**Issue by mmikowski** [wimpysworld/deb-get#126] opened 2022-05-07 21:27 UTC
**I will provide a pull request,** but I wanted to let you know asap:

## Summary

The `dpkg -l` test reports a package as installed even if it isn't.

## How to Reproduce

```
sudo apt remove dropbox
if dpkg -l dropbox; then
  echo 'Dropbox is installed'
fi
```

Actual results: Dropbox is reported as installed
Expected results: Dropbox should NOT be reported as installed
Occurrence: This occurs when packages are removed, not when purged

## Analysis

In the above example, Dropbox is reported with a status of 'rc' (removed, config files intact), which is interpreted as installed.

## Solution
Use this function instead (adjust for style as needed). This is unit tested and also passes shellcheck and bash support-pro:

```
## BEGIN _chkInstalledPkgFn {
# Summary  : _chkInstalledPkgFn <package-name>;
# Purpose  : Quickly check if a package is installed
# Example  : _chkInstalledPkgFn kfocus-nvidia;
# Returns  : 0 = package installed; 1 = not installed
# Throws   : none
#
_chkInstalledPkgFn () {
  declare _pkg_name _status_str;
  _pkg_name="${1:-}";
  _status_str="$( 2>&1 \
    dpkg-query -f '${db:Status-abbrev}' -W "${_pkg_name}"
  )"; 
  if grep -qE '^.i ' <<< "${_status_str}"; then return 0; fi
  return 1;
}
## . END _chkInstalledPkgFn }
```

FWIW, I discovered that `apt list --installed` provided the correct information, as does `apt-cache policy "$pkg"`. `wajig list-installed`, however, shows a similar issue.

**Comment by flexiondotorg** [comment] 2022-05-08 09:25
Duplicate of #36

Please consider submitting a pull request with the improvements you've suggested @mmikowski :slightly_smiling_face:

**Closed by flexiondotorg** 2022-05-08 09:25 UTC
